### ISSUE TITLE
请教顺丰问题

### ISSUE THREAD

**Issue by vay1314** [chavyleung/scripts#334]
首先感谢作者，遇到个问题请教下
运行环境：elecV2P
运行脚本：顺丰sfexpress.js
在elecV2P自动抓取并存储chavy_login_sfexpress，但运行sfexpress.js时提示Cannot read property 'taskTitleLevels' of undefined，请教taskTitleLevels这个有办法解决吗

**Comment by vay1314** [comment]
顺便请教下如想本地node运行js，那抓取的变量怎么使用呢

**Comment by vay1314** [comment]
@chavyleung 请教是不能用node本地运行吗？

**Comment by chavyleung** [comment]
可以

**Comment by vay1314** [comment]
> 可以

请教本地运行时，变量chavy_login_sfexpress在哪写入？直接改js脚本里面吗

**Comment by chavyleung** [comment]
可以直接写在代码里
也可以把boxjs的数据备份下来（全局备份），然后在项目根目录另存名为box.dat的文件

**Comment by vay1314** [comment]
> 可以直接写在代码里
> 也可以把boxjs的数据备份下来（全局备份），然后在项目根目录另存名为box.dat的文件

我直接改js会报错，现在身边没ios设备导出不了boxjs，请教有没有box.dat内变量内容的格式？我直接创建下这个文件试试。十分感谢

**Comment by chavyleung** [comment]
```json
{
    "chavy_login_sfexpress": ""
}
```

这样试试

**Comment by vay1314** [comment]
> ```json
> {
>     "chavy_login_sfexpress": ""
> }
> ```
> 
> 这样试试

测试不行，chavy_login_sfexpress我看是个json格式，我压缩后填入"chavy_login_sfexpress": ""中，执行node js脚本会报以下错误。
TypeError: Cannot read property 'headers' of undefined
    at loginapp (/usr/local/app/script/Shell/sfexpress/sfexpress.js:19:20)
    at /usr/local/app/script/Shell/sfexpress/sfexpress.js:5:9
    at Object.<anonymous> (/usr/local/app/script/Shell/sfexpress/sfexpress.js:13:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
